version: '3.8'
services:
  api:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - my_db

  my_db:
    restart: on-failure
    image: "postgres:latest"
    environment:
      POSTGRES_DB: 'mydb'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'

    volumes:
      - type: bind
        source: ./static
        target: /var/lib/postgresql/data
